# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1060, 757)
        Form.setMinimumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(9)
        Form.setFont(font)
        Form.setStyleSheet("QWidget {\n"
"border-image:url(D:/Python practise/practise/PCA/cover.png);\n"
"}\n"
"\n"
"QFrame {\n"
"\n"
"border-image:url();\n"
"\n"
"}\n"
"QPushButton {\n"
"border-image:url();\n"
"\n"
"}\n"
"QToolButton {\n"
"\n"
"border-image:url();\n"
"\n"
"}\n"
"QLineEdit {\n"
"\n"
"border-image:url();\n"
"\n"
"}\n"
"QGroupBox {\n"
"\n"
"border-image:url();\n"
"\n"
"}\n"
"QLabel {\n"
"\n"
"border-image:url();\n"
"\n"
"}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(350, 30, 361, 51))
        font = QtGui.QFont()
        font.setFamily("华光胖头鱼_CNKI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color:rgb(93, 93, 93);\n"
"}")
        self.label.setObjectName("label")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(760, 380, 50, 24))
        self.toolButton.setStyleSheet("QToolButton{\n"
"    background-color: rgb(255, 255, 255, 0);\n"
"}\n"
"\n"
"\n"
"QToolButton:hover\n"
"{\n"
"    \n"
"    color: rgb(163, 163, 163);\n"
"    border-color: rgb(115, 115, 115);\n"
"}\n"
"")
        self.toolButton.setObjectName("toolButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(120, 370, 631, 40))
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255, 180);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(810, 370, 111, 40))
        self.pushButton.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    font: 11pt \"黑体\";\n"
"    background-color: qlineargradient(spread:repeat, x1:0.408, y1:0, x2:0.408, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(178, 178, 178, 255));\n"
"    \n"
"    background-color: qlineargradient(spread:repeat, x1:0.408, y1:0, x2:0.408, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(219, 219, 219, 255));\n"
"    color:rgb(93, 93, 93);\n"
"\n"
"    border-radius: 5px;\n"
"    \n"
"    border-color: rgb(115, 115, 115);\n"
"\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    \n"
"    color: rgb(163, 163, 163);\n"
"    border-color: rgb(115, 115, 115);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(380, 120, 291, 181))
        self.frame_2.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(120, 120, 120);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 70, 111, 40))
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    font: 11pt \"黑体\";\n"
"    background-color: qlineargradient(spread:repeat, x1:0.408, y1:0, x2:0.408, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(178, 178, 178, 255));\n"
"    \n"
"    background-color: qlineargradient(spread:repeat, x1:0.408, y1:0, x2:0.408, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(219, 219, 219, 255));\n"
"    color:rgb(93, 93, 93);\n"
"\n"
"    border-radius: 5px;\n"
"    \n"
"    border-color: rgb(115, 115, 115);\n"
"\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    \n"
"    color: rgb(163, 163, 163);\n"
"    border-color: rgb(115, 115, 115);\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 10, 111, 40))
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    font: 11pt \"黑体\";\n"
"    background-color: qlineargradient(spread:repeat, x1:0.408, y1:0, x2:0.408, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(178, 178, 178, 255));\n"
"    \n"
"    background-color: qlineargradient(spread:repeat, x1:0.408, y1:0, x2:0.408, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(219, 219, 219, 255));\n"
"    color:rgb(93, 93, 93);\n"
"\n"
"    border-radius: 5px;\n"
"    \n"
"    border-color: rgb(115, 115, 115);\n"
"\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    \n"
"    color: rgb(163, 163, 163);\n"
"    border-color: rgb(115, 115, 115);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 130, 111, 40))
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    font: 11pt \"黑体\";\n"
"    background-color: qlineargradient(spread:repeat, x1:0.408, y1:0, x2:0.408, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(178, 178, 178, 255));\n"
"    \n"
"    background-color: qlineargradient(spread:repeat, x1:0.408, y1:0, x2:0.408, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(219, 219, 219, 255));\n"
"    color:rgb(93, 93, 93);\n"
"\n"
"    border-radius: 5px;\n"
"    \n"
"    border-color: rgb(115, 115, 115);\n"
"\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    \n"
"    color: rgb(163, 163, 163);\n"
"    border-color: rgb(115, 115, 115);\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 120, 160))
        self.label_4.setStyleSheet("QLabel{border-radius:7px;background-color: rgb(255, 255, 255);border:0px;}\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(110, 460, 141, 211))
        self.frame_3.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(120, 120, 120);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(40, 180, 71, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"color:rgb(85, 80, 80);\n"
"border:0px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 120, 160))
        self.label_5.setStyleSheet("QLabel{border-radius:7px;background-color: rgb(255, 255, 255);border:0px;}\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(280, 460, 661, 211))
        self.frame.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(120, 120, 120);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(260, 180, 151, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"color:rgb(85, 80, 80);\n"
"border:0px;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 120, 160))
        self.label_10.setStyleSheet("QLabel{border-radius:7px;background-color: rgb(255, 255, 255);border:0px;}\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(140, 10, 120, 160))
        self.label_9.setStyleSheet("QLabel{border-radius:7px;background-color: rgb(255, 255, 255);border:0px;}\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(270, 10, 120, 160))
        self.label_7.setStyleSheet("QLabel{border-radius:7px;background-color: rgb(255, 255, 255);border:0px;}\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(400, 10, 120, 160))
        self.label_8.setStyleSheet("QLabel{border-radius:7px;background-color: rgb(255, 255, 255);border:0px;}\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(530, 10, 120, 160))
        self.label_6.setStyleSheet("QLabel{border-radius:7px;background-color: rgb(255, 255, 255);border:0px;}\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(380, 700, 111, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel{\n"
"color:rgb(85, 80, 80);\n"
"border:0px;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(510, 690, 91, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel{\n"
"color:rgb(9, 9, 9);\n"
"border:0px;\n"
"}")
        self.label_12.setObjectName("label_12")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "PCA人脸识别系统"))
        self.toolButton.setText(_translate("Form", "..."))
        self.lineEdit.setPlaceholderText(_translate("Form", "输入照片位置"))
        self.pushButton.setText(_translate("Form", "确 定"))
        self.pushButton_4.setText(_translate("Form", "关闭摄像头"))
        self.pushButton_2.setText(_translate("Form", "打开摄像头"))
        self.pushButton_3.setText(_translate("Form", "拍 摄"))
        self.label_2.setText(_translate("Form", "测试脸"))
        self.label_3.setText(_translate("Form", "最相似的5张人脸"))
        self.label_11.setText(_translate("Form", "识别结果为："))
        self.label_12.setText(_translate("Form", ""))
